// dimensions.ts
export const NuskaDimensions = {
    MARGIN_SMALL: 5,
    MARGIN_DEFAULT: 10,
    MARGIN_MEDIUM: 16,
    MARGIN_LARGE: 20,
    MARGIN_XX_LARGE: 40,
    PADDING_DEFAULT: 15,
    PADDING_SMALL: 5,
    PADDING_CATEGORY_EXPANDED: 8,
    PADDING_MEDIUM: 10,
    PADDING_LARGE: 20,
    PADDING_XX_LARGE: 40,
    BORDER_RADIUS_CARD: 5,

    // height and width
    MEDIUM_HEIGHT: 50,
    DEFAULT_HEIGHT: 40,
    BUTTON_HEIGHT: 45,
    DEFAULT_SEARCH_BAR_HEIGHT: 45,

    // width
    WIDTH_DEFAULT: 100,
    HEIGHT_DEFAULT: 100,

};

